[project]
name = "marketingimagegen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fonttools>=4.57.0",
    "pillow>=11.2.1",
    "requests>=2.32.3",
]
